development:
  adapter: postgresql
  encoding: unicode
  database: fav_bands_development
  pool: 5
  username: DarthNeel
  password:
  host: localhost

test:
  adapter: postgresql
  encoding: unicode
  database: fav_bands_test
  pool: 5
  username: DarthNeel
  password:
  host: localhost

production:
  adapter: postgresql
  encoding: unicode
  database: fav_bands_production
  pool: 5
  username: DarthNeel
  password:
  host: localhost